<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./css/one.css" ?>
<!DOCTYPE one [
  <!ENTITY titlee "Название товара">
  <!ENTITY scrip "Описание товара">
  <!ENTITY money "Цена">
  <!ENTITY d "$">
  <!ELEMENT one (headd, tovar+)>
  <!ELEMENT headd (titlee, scrip, money)>
  <!ELEMENT tovar (name, description, price)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
]>
<one>
  <headd>
    <titlee>&titlee;</titlee>
    <scrip>&scrip;</scrip>
    <money>&money;</money>
  </headd>

  <tovar>
    <name>Ноутбук</name>
    <description>Мощный ноутбук для работы и игр.</description>
    <price>50000 &d;</price>
  </tovar>

  <tovar>
    <name>Смартфон</name>
    <description>Смартфон с отличной камерой и производительностью.</description>
    <price>25000 &d;</price>
  </tovar>

  <tovar>
    <name>Наушники</name>
    <description>Беспроводные наушники с хорошим звуком.</description>
    <price>5000 &d;</price>
  </tovar>

  <tovar>
    <name>Клавиатура</name>
    <description>Механическая клавиатура с RGB-подсветкой.</description>
    <price>3500 &d;</price>
  </tovar>

  <tovar>
    <name>Монитор</name>
    <description>Монитор с разрешением 4K и хорошими углами обзора.</description>
    <price>15000 &d;</price>
  </tovar>
</one>
